version: 2

defaults:
  workspace_root: &workspace_root
    ~/circleci-samples

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8

  golang_container: &golang_container
    working_directory: *workspace_root
    docker:
      - image: circleci/golang:1

  filters: &default_filters
    tags:
      only: '/v[0-9]+(\.[0-9]+)*/'

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-samples-node-{{ checksum "yarn.lock" }}
        - v1-samples-node-

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-samples-yarn-{{ checksum "yarn.lock" }}
            - v1-samples-yarn-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          key: v1-samples-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: v1-samples-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  lint:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Lint JavaScript
          command: yarn lint


  release:
    <<: *golang_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Install github-release
          command: go get github.com/aktau/github-release

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - checkout:
          filters: *default_filters

      - install:
          requires:
            - checkout
          filters: *default_filters

      - lint:
          requires:
            - install
          filters: *default_filters

      - release:
          requires:
            - lint
          filters:
            <<: *default_filters
            branches:
              ignore: '/.*/'
